### ISSUE TITLE
Facebook Authentication 

### ISSUE THREAD

**Issue by AhmedAdelIbrahim** [myriameayman/Raye7-#21]

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman @renadshaaban @som3a123 @ebrahim-elgaml @MariamTalaat @mahatalaat 
PLEASE REVIEW ME

**Comment by renadshaaban** [comment]
@AhmedAdelIbrahim its fine (Y)

**Comment by AhmedAdelIbrahim** [comment]
@renadshaaban Ok , Thank you

**Comment by AhmedAdelIbrahim** [comment]
@mahatalaat @ebrahim-elgaml  Please review my code

**Comment by mahatalaat** [comment]
@AhmedAdelIbrahim  done

**Comment by AhmedAdelIbrahim** [comment]
@mahatalaat Thank you very much

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman Please review me
