### ISSUE TITLE
offering ride  

### ISSUE THREAD

**Issue by myriameayman** [myriameayman/Raye7-#25]

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim , @mahatalaat , @renadshaaban , @ebrahim-elgaml , @som3a123 , @MariamTalaat 
plz review me

**Comment by renadshaaban** [comment]
@myriameayman  as for UML diagram why is the user clicks on new request takes 1.x ? It should be 2

**Comment by renadshaaban** [comment]
@myriameayman it is okay :dancer:

**Comment by mahatalaat** [comment]
@myriameayman  
In all the files you edited the 1st letter after the hash must be capitalized and the end of each comment must have a dot  so please check them all 
in the controller part : Lines 35 and 36 leave space between # and 1st letter/symbol 
in the view part: I couldnot find any code in the gecoding and the reverse_gecoding , as for the create file line 73 its function not fumction ¨typo¨ , and line 95 leave space

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman Done with the test review and the testing is working fine

**Comment by mahatalaat** [comment]
@myriameayman  perfect
