### ISSUE TITLE
join a specific trip

### ISSUE THREAD

**Issue by renadshaaban** [myriameayman/Raye7-#37]

**Comment by renadshaaban** [comment]
@AhmedAdelIbrahim  @ebrahim-elgaml  @MariamTalaat  @som3a123 @ebrahim-elgaml  plz review this issue

**Comment by renadshaaban** [comment]
@myriameayman  @ebrahim-elgaml  @AhmedAdelIbrahim  @som3a123  @mahatalaat  @MariamTalaat

**Comment by mahatalaat** [comment]
@renadshaaban  line number 4 in trips controller needs to be capitalized 
 and in the myaccount view you are missing many closing documentations
